import { Inter } from 'next/font/google';
import "./globals.css";

const inter = Inter({
  subsets: ['latin'], // أو 'latin-ext' لو عايز دعم عربي/أحرف إضافية
  variable: '--font-inter', // لو عايز تستخدمه في CSS variable
  weight: ['100', '200' , '300' ,'400', '500', '700'], // اختياري: أنواع الأوزان اللي محتاجها
});

export const metadata = {
  title: 'My Next App',
  description: 'Generated by Next.js',
   icons: {
    icon: "icon2.png",
  },
};

 

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={inter.variable}>
      <body>{children}</body>
    </html>
  );
}
